name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - matplotlib
  - jupyterlab
  - pandas
  - seaborn
  - scipy
  - sklearn
  - skfuzzy
  - pymysql
  - google
  - pip:
    - jupyterlab_latex
