name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - matplotlib
  - jupyterlab
  - pandas
  - seaborn
  - scipy
  - pymysql
  - pip:
    - jupyterlab_latex
    - scikit-fuzzy
    - scikit-learn
