#!/bin/bash

# install JupyterLab extension
jupyter labextension install @jupyterlab/latex

# prints pwd to check.txt

echo $PWD check.txt

# creates jupyter config file

mkdir .jupyter
cp .binder/jupyter_notebook_config.py .jupyter/jupyter_notebook_config.py
