#!/bin/bash

# install JupyterLab extension
jupyter labextension install @jupyterlab/latex

# creates jupyter config file

mkdir .jupyter
cp jupyter_notebook_config.py .jupyter/jupyter_notebook_config.py
